using System.Text;
using ROSettaDDS.MsgGen.Model;
using ROSettaDDS.MsgGen.TypeMapping;

namespace ROSettaDDS.MsgGen.Emitting;

/// <summary>
/// .srv 1 件につき <c>&lt;Service&gt;Service</c> 静的クラスを生成する。
/// このクラスは <c>ServiceDescriptor&lt;TRequest, TResponse&gt;</c> 型の <c>Descriptor</c> を公開し、
/// クライアント生成 API へ型名・シリアライザを一括で渡せるようにする。
/// </summary>
public sealed class ServiceDescriptorEmitter
{
    private readonly TypeNameResolver _resolver;

    public ServiceDescriptorEmitter(TypeNameResolver? resolver = null)
    {
        _resolver = resolver ?? new TypeNameResolver();
    }

    public string Emit(string package, string serviceName, MessageDefinition request, MessageDefinition response)
    {
        string ns = _resolver.Namespace(package);
        string reqType = _resolver.CSharpTypeName(package, request.Name);
        string respType = _resolver.CSharpTypeName(package, response.Name);
        string reqSer = _resolver.SerializerName(package, request.Name);
        string respSer = _resolver.SerializerName(package, response.Name);
        string reqDds = _resolver.DdsTypeName(package, request.SubNamespace, request.Name);
        string respDds = _resolver.DdsTypeName(package, response.SubNamespace, response.Name);
        string className = NamingConventions.ToPascalCase(serviceName) + "Service";

        var sb = new StringBuilder();
        sb.Append("// <auto-generated>\n");
        sb.Append("//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。\n");
        sb.Append("//     source: " + package + "/srv/" + serviceName + "\n");
        sb.Append("// </auto-generated>\n");
        sb.Append("using ROSettaDDS.Dds;\n\n");
        sb.Append("namespace " + ns + "\n{\n");
        sb.Append("    public static class " + className + "\n    {\n");
        sb.Append("        public static readonly ServiceDescriptor<" + reqType + ", " + respType + "> Descriptor =\n");
        sb.Append("            new ServiceDescriptor<" + reqType + ", " + respType + ">(\n");
        sb.Append("                requestDdsTypeName: \"" + reqDds + "\",\n");
        sb.Append("                responseDdsTypeName: \"" + respDds + "\",\n");
        sb.Append("                requestSerializer: " + reqSer + ".Instance,\n");
        sb.Append("                responseSerializer: " + respSer + ".Instance);\n");
        sb.Append("    }\n");
        sb.Append("}\n");
        return sb.ToString();
    }
}
