# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "commander-15.0.0" = {
      name = "commander";
      packageName = "commander";
      version = "15.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-15.0.0.tgz";
        sha512 = "z67u4ZhzCL/Tydu1lJARtEZYWbWaN7oYLHbsuzocr6y4N6WZAagG3RQ4FW61V1/0+jImpj293XfrcYnd1qxtPg==";
      };
    };
    "launch-unity-0.17.1" = {
      name = "launch-unity";
      packageName = "launch-unity";
      version = "0.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/launch-unity/-/launch-unity-0.17.1.tgz";
        sha512 = "Cfb2jgdkz/4K7AN/J9fYyzdVTKDavXzTRTNUEjSAriKyqsLyNkz0g/6SA475jIjjGyaZj50m/CFcU+ZK5rgmlg==";
      };
    };
    "semver-7.8.1" = {
      name = "semver";
      packageName = "semver";
      version = "7.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.8.1.tgz";
        sha512 = "rkVq3IXh+4FDGch+KwzX3aV9W3kO54GyEgpvBzSyctDA6Xtd7RJQV1xmXbeQp5v7+VzLOfVqiutSE6GICgPFvg==";
      };
    };
  };
in
{
  "uloop-cli-2.1.6" = nodeEnv.buildNodePackage {
    name = "uloop-cli";
    packageName = "uloop-cli";
    version = "2.1.6";
    src = fetchurl {
      url = "https://registry.npmjs.org/uloop-cli/-/uloop-cli-2.1.6.tgz";
      sha512 = "e3bieo8Ps9lrYRqGqW/90ahrRmUc5+jhpM/m0y3bSOHB0NhZ60yRV6Qzk/iaw5GPbxhTqn3byjHouU+PTNYSYw==";
    };
    dependencies = [
      sources."commander-15.0.0"
      sources."launch-unity-0.17.1"
      sources."semver-7.8.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "CLI tool for Unity Editor communication via Unity CLI Loop";
      homepage = "https://github.com/hatayama/uLoopMCP#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
