// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/Accel
// </auto-generated>
using ROSettaDDS.Cdr;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/Accel の C# 表現 (生成コード)。
    /// </summary>
    public struct Accel
    {
        public const string RosTypeName = "geometry_msgs/msg/Accel";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::Accel_";

        public Vector3 Linear;
        public Vector3 Angular;

        public Accel(Vector3 linear, Vector3 angular)
        {
            Linear = linear;
            Angular = angular;
        }

        public override string ToString() => $"Accel(linear={Linear}, angular={Angular})";
    }

    public sealed class AccelSerializer : ICdrSerializer<Accel>
    {
        public static readonly AccelSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in Accel value)
        {
            int total = 0;
            total += Vector3Serializer.Instance.GetSerializedSize(in value.Linear);
            total += Vector3Serializer.Instance.GetSerializedSize(in value.Angular);
            return total;
        }

        public void Serialize(ref CdrWriter writer, in Accel value)
        {
            Vector3Serializer.Instance.Serialize(ref writer, in value.Linear);
            Vector3Serializer.Instance.Serialize(ref writer, in value.Angular);
        }

        public void Deserialize(ref CdrReader reader, out Accel value)
        {
            Vector3Serializer.Instance.Deserialize(ref reader, out Vector3 linear);
            Vector3Serializer.Instance.Deserialize(ref reader, out Vector3 angular);
            value = new Accel(linear, angular);
        }

        public void SerializeKey(ref CdrWriter writer, in Accel value)
        {
        }
    }
}
