// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/AccelWithCovariance
// </auto-generated>
using ROSettaDDS.Cdr;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/AccelWithCovariance の C# 表現 (生成コード)。
    /// </summary>
    public struct AccelWithCovariance
    {
        public const string RosTypeName = "geometry_msgs/msg/AccelWithCovariance";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::AccelWithCovariance_";

        public Accel Accel;
        public double[] Covariance;

        public AccelWithCovariance(Accel accel, double[] covariance)
        {
            Accel = accel;
            Covariance = covariance;
        }

        public override string ToString() => $"AccelWithCovariance(accel={Accel}, covariance=[{(Covariance is null ? 0 : Covariance.Length)}])";
    }

    public sealed class AccelWithCovarianceSerializer : ICdrSerializer<AccelWithCovariance>
    {
        public static readonly AccelWithCovarianceSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in AccelWithCovariance value)
        {
            int total = 0;
            total += AccelSerializer.Instance.GetSerializedSize(in value.Accel);
            total += 36 * 8;
            return total;
        }

        public void Serialize(ref CdrWriter writer, in AccelWithCovariance value)
        {
            AccelSerializer.Instance.Serialize(ref writer, in value.Accel);
            var arrCovariance = value.Covariance ?? new double[36];
            for (int i = 0; i < 36; i++)
            {
                writer.WriteDouble(arrCovariance[i]);
            }
        }

        public void Deserialize(ref CdrReader reader, out AccelWithCovariance value)
        {
            AccelSerializer.Instance.Deserialize(ref reader, out Accel accel);
            var covariance = new double[36];
            for (int i = 0; i < 36; i++)
            {
                covariance[i] = reader.ReadDouble();
            }
            value = new AccelWithCovariance(accel, covariance);
        }

        public void SerializeKey(ref CdrWriter writer, in AccelWithCovariance value)
        {
        }
    }
}
