// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/AccelStamped
// </auto-generated>
using ROSettaDDS.Cdr;
using ROSettaDDS.Msgs.Std;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/AccelStamped の C# 表現 (生成コード)。
    /// </summary>
    public struct AccelStamped
    {
        public const string RosTypeName = "geometry_msgs/msg/AccelStamped";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::AccelStamped_";

        public Header Header;
        public Accel Accel;

        public AccelStamped(Header header, Accel accel)
        {
            Header = header;
            Accel = accel;
        }

        public override string ToString() => $"AccelStamped(header={Header}, accel={Accel})";
    }

    public sealed class AccelStampedSerializer : ICdrSerializer<AccelStamped>
    {
        public static readonly AccelStampedSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in AccelStamped value)
        {
            int total = 0;
            total += HeaderSerializer.Instance.GetSerializedSize(in value.Header);
            total += 7;
            total += AccelSerializer.Instance.GetSerializedSize(in value.Accel);
            return total;
        }

        public void Serialize(ref CdrWriter writer, in AccelStamped value)
        {
            HeaderSerializer.Instance.Serialize(ref writer, in value.Header);
            AccelSerializer.Instance.Serialize(ref writer, in value.Accel);
        }

        public void Deserialize(ref CdrReader reader, out AccelStamped value)
        {
            HeaderSerializer.Instance.Deserialize(ref reader, out Header header);
            AccelSerializer.Instance.Deserialize(ref reader, out Accel accel);
            value = new AccelStamped(header, accel);
        }

        public void SerializeKey(ref CdrWriter writer, in AccelStamped value)
        {
        }
    }
}
