// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/AccelWithCovarianceStamped
// </auto-generated>
using ROSettaDDS.Cdr;
using ROSettaDDS.Msgs.Std;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/AccelWithCovarianceStamped の C# 表現 (生成コード)。
    /// </summary>
    public struct AccelWithCovarianceStamped
    {
        public const string RosTypeName = "geometry_msgs/msg/AccelWithCovarianceStamped";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::AccelWithCovarianceStamped_";

        public Header Header;
        public AccelWithCovariance Accel;

        public AccelWithCovarianceStamped(Header header, AccelWithCovariance accel)
        {
            Header = header;
            Accel = accel;
        }

        public override string ToString() => $"AccelWithCovarianceStamped(header={Header}, accel={Accel})";
    }

    public sealed class AccelWithCovarianceStampedSerializer : ICdrSerializer<AccelWithCovarianceStamped>
    {
        public static readonly AccelWithCovarianceStampedSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in AccelWithCovarianceStamped value)
        {
            int total = 0;
            total += HeaderSerializer.Instance.GetSerializedSize(in value.Header);
            total += 7;
            total += AccelWithCovarianceSerializer.Instance.GetSerializedSize(in value.Accel);
            return total;
        }

        public void Serialize(ref CdrWriter writer, in AccelWithCovarianceStamped value)
        {
            HeaderSerializer.Instance.Serialize(ref writer, in value.Header);
            AccelWithCovarianceSerializer.Instance.Serialize(ref writer, in value.Accel);
        }

        public void Deserialize(ref CdrReader reader, out AccelWithCovarianceStamped value)
        {
            HeaderSerializer.Instance.Deserialize(ref reader, out Header header);
            AccelWithCovarianceSerializer.Instance.Deserialize(ref reader, out AccelWithCovariance accel);
            value = new AccelWithCovarianceStamped(header, accel);
        }

        public void SerializeKey(ref CdrWriter writer, in AccelWithCovarianceStamped value)
        {
        }
    }
}
