// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/InertiaStamped
// </auto-generated>
using ROSettaDDS.Cdr;
using ROSettaDDS.Msgs.Std;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/InertiaStamped の C# 表現 (生成コード)。
    /// </summary>
    public struct InertiaStamped
    {
        public const string RosTypeName = "geometry_msgs/msg/InertiaStamped";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::InertiaStamped_";

        public Header Header;
        public Inertia Inertia;

        public InertiaStamped(Header header, Inertia inertia)
        {
            Header = header;
            Inertia = inertia;
        }

        public override string ToString() => $"InertiaStamped(header={Header}, inertia={Inertia})";
    }

    public sealed class InertiaStampedSerializer : ICdrSerializer<InertiaStamped>
    {
        public static readonly InertiaStampedSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in InertiaStamped value)
        {
            int total = 0;
            total += HeaderSerializer.Instance.GetSerializedSize(in value.Header);
            total += 7;
            total += InertiaSerializer.Instance.GetSerializedSize(in value.Inertia);
            return total;
        }

        public void Serialize(ref CdrWriter writer, in InertiaStamped value)
        {
            HeaderSerializer.Instance.Serialize(ref writer, in value.Header);
            InertiaSerializer.Instance.Serialize(ref writer, in value.Inertia);
        }

        public void Deserialize(ref CdrReader reader, out InertiaStamped value)
        {
            HeaderSerializer.Instance.Deserialize(ref reader, out Header header);
            InertiaSerializer.Instance.Deserialize(ref reader, out Inertia inertia);
            value = new InertiaStamped(header, inertia);
        }

        public void SerializeKey(ref CdrWriter writer, in InertiaStamped value)
        {
        }
    }
}
