// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/Inertia
// </auto-generated>
using ROSettaDDS.Cdr;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/Inertia の C# 表現 (生成コード)。
    /// </summary>
    public struct Inertia
    {
        public const string RosTypeName = "geometry_msgs/msg/Inertia";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::Inertia_";

        public double M;
        public Vector3 Com;
        public double Ixx;
        public double Ixy;
        public double Ixz;
        public double Iyy;
        public double Iyz;
        public double Izz;

        public Inertia(double m, Vector3 com, double ixx, double ixy, double ixz, double iyy, double iyz, double izz)
        {
            M = m;
            Com = com;
            Ixx = ixx;
            Ixy = ixy;
            Ixz = ixz;
            Iyy = iyy;
            Iyz = iyz;
            Izz = izz;
        }

        public override string ToString() => $"Inertia(m={M}, com={Com}, ixx={Ixx}, ixy={Ixy}, ixz={Ixz}, iyy={Iyy}, iyz={Iyz}, izz={Izz})";
    }

    public sealed class InertiaSerializer : ICdrSerializer<Inertia>
    {
        public static readonly InertiaSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in Inertia value)
        {
            int total = 0;
            total += 8;
            total += Vector3Serializer.Instance.GetSerializedSize(in value.Com);
            total += 8;
            total += 8;
            total += 8;
            total += 8;
            total += 8;
            total += 8;
            return total;
        }

        public void Serialize(ref CdrWriter writer, in Inertia value)
        {
            writer.WriteDouble(value.M);
            Vector3Serializer.Instance.Serialize(ref writer, in value.Com);
            writer.WriteDouble(value.Ixx);
            writer.WriteDouble(value.Ixy);
            writer.WriteDouble(value.Ixz);
            writer.WriteDouble(value.Iyy);
            writer.WriteDouble(value.Iyz);
            writer.WriteDouble(value.Izz);
        }

        public void Deserialize(ref CdrReader reader, out Inertia value)
        {
            double m = reader.ReadDouble();
            Vector3Serializer.Instance.Deserialize(ref reader, out Vector3 com);
            double ixx = reader.ReadDouble();
            double ixy = reader.ReadDouble();
            double ixz = reader.ReadDouble();
            double iyy = reader.ReadDouble();
            double iyz = reader.ReadDouble();
            double izz = reader.ReadDouble();
            value = new Inertia(m, com, ixx, ixy, ixz, iyy, iyz, izz);
        }

        public void SerializeKey(ref CdrWriter writer, in Inertia value)
        {
        }
    }
}
