// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/PointStamped
// </auto-generated>
using ROSettaDDS.Cdr;
using ROSettaDDS.Msgs.Std;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/PointStamped の C# 表現 (生成コード)。
    /// </summary>
    public struct PointStamped
    {
        public const string RosTypeName = "geometry_msgs/msg/PointStamped";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::PointStamped_";

        public Header Header;
        public Point Point;

        public PointStamped(Header header, Point point)
        {
            Header = header;
            Point = point;
        }

        public override string ToString() => $"PointStamped(header={Header}, point={Point})";
    }

    public sealed class PointStampedSerializer : ICdrSerializer<PointStamped>
    {
        public static readonly PointStampedSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in PointStamped value)
        {
            int total = 0;
            total += HeaderSerializer.Instance.GetSerializedSize(in value.Header);
            total += 7;
            total += PointSerializer.Instance.GetSerializedSize(in value.Point);
            return total;
        }

        public void Serialize(ref CdrWriter writer, in PointStamped value)
        {
            HeaderSerializer.Instance.Serialize(ref writer, in value.Header);
            PointSerializer.Instance.Serialize(ref writer, in value.Point);
        }

        public void Deserialize(ref CdrReader reader, out PointStamped value)
        {
            HeaderSerializer.Instance.Deserialize(ref reader, out Header header);
            PointSerializer.Instance.Deserialize(ref reader, out Point point);
            value = new PointStamped(header, point);
        }

        public void SerializeKey(ref CdrWriter writer, in PointStamped value)
        {
        }
    }
}
