// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/Point32
// </auto-generated>
using ROSettaDDS.Cdr;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/Point32 の C# 表現 (生成コード)。
    /// </summary>
    public struct Point32
    {
        public const string RosTypeName = "geometry_msgs/msg/Point32";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::Point32_";

        public float X;
        public float Y;
        public float Z;

        public Point32(float x, float y, float z)
        {
            X = x;
            Y = y;
            Z = z;
        }

        public override string ToString() => $"Point32(x={X}, y={Y}, z={Z})";
    }

    public sealed class Point32Serializer : ICdrSerializer<Point32>
    {
        public static readonly Point32Serializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in Point32 value)
        {
            int total = 0;
            total += 4;
            total += 4;
            total += 4;
            return total;
        }

        public void Serialize(ref CdrWriter writer, in Point32 value)
        {
            writer.WriteFloat(value.X);
            writer.WriteFloat(value.Y);
            writer.WriteFloat(value.Z);
        }

        public void Deserialize(ref CdrReader reader, out Point32 value)
        {
            float x = reader.ReadFloat();
            float y = reader.ReadFloat();
            float z = reader.ReadFloat();
            value = new Point32(x, y, z);
        }

        public void SerializeKey(ref CdrWriter writer, in Point32 value)
        {
        }
    }
}
