// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/Polygon
// </auto-generated>
using ROSettaDDS.Cdr;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/Polygon の C# 表現 (生成コード)。
    /// </summary>
    public struct Polygon
    {
        public const string RosTypeName = "geometry_msgs/msg/Polygon";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::Polygon_";

        public Point32[] Points;

        public Polygon(Point32[] points)
        {
            Points = points;
        }

        public override string ToString() => $"Polygon(points=[{(Points is null ? 0 : Points.Length)}])";
    }

    public sealed class PolygonSerializer : ICdrSerializer<Polygon>
    {
        public static readonly PolygonSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in Polygon value)
        {
            int total = 0;
            total += 4;
            if (value.Points is not null)
            {
                var serPoints = Point32Serializer.Instance;
                foreach (ref readonly var ePoints in value.Points.AsSpan())
                {
                    total += 3;
                    total += serPoints.GetSerializedSize(in ePoints);
                }
            }
            return total;
        }

        public void Serialize(ref CdrWriter writer, in Polygon value)
        {
            var arrPoints = value.Points ?? System.Array.Empty<Point32>();
            writer.WriteSequenceLength(arrPoints.Length);
            foreach (var ePoints in arrPoints)
            {
                Point32Serializer.Instance.Serialize(ref writer, in ePoints);
            }
        }

        public void Deserialize(ref CdrReader reader, out Polygon value)
        {
            int pointsCount = reader.ReadSequenceLength();
            var points = pointsCount == 0 ? System.Array.Empty<Point32>() : new Point32[pointsCount];
            for (int i = 0; i < pointsCount; i++)
            {
                Point32Serializer.Instance.Deserialize(ref reader, out points[i]);
            }
            value = new Polygon(points);
        }

        public void SerializeKey(ref CdrWriter writer, in Polygon value)
        {
        }
    }
}
