// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/PolygonStamped
// </auto-generated>
using ROSettaDDS.Cdr;
using ROSettaDDS.Msgs.Std;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/PolygonStamped の C# 表現 (生成コード)。
    /// </summary>
    public struct PolygonStamped
    {
        public const string RosTypeName = "geometry_msgs/msg/PolygonStamped";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::PolygonStamped_";

        public Header Header;
        public Polygon Polygon;

        public PolygonStamped(Header header, Polygon polygon)
        {
            Header = header;
            Polygon = polygon;
        }

        public override string ToString() => $"PolygonStamped(header={Header}, polygon={Polygon})";
    }

    public sealed class PolygonStampedSerializer : ICdrSerializer<PolygonStamped>
    {
        public static readonly PolygonStampedSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in PolygonStamped value)
        {
            int total = 0;
            total += HeaderSerializer.Instance.GetSerializedSize(in value.Header);
            total += 3;
            total += PolygonSerializer.Instance.GetSerializedSize(in value.Polygon);
            return total;
        }

        public void Serialize(ref CdrWriter writer, in PolygonStamped value)
        {
            HeaderSerializer.Instance.Serialize(ref writer, in value.Header);
            PolygonSerializer.Instance.Serialize(ref writer, in value.Polygon);
        }

        public void Deserialize(ref CdrReader reader, out PolygonStamped value)
        {
            HeaderSerializer.Instance.Deserialize(ref reader, out Header header);
            PolygonSerializer.Instance.Deserialize(ref reader, out Polygon polygon);
            value = new PolygonStamped(header, polygon);
        }

        public void SerializeKey(ref CdrWriter writer, in PolygonStamped value)
        {
        }
    }
}
