// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/PoseWithCovariance
// </auto-generated>
using ROSettaDDS.Cdr;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/PoseWithCovariance の C# 表現 (生成コード)。
    /// </summary>
    public struct PoseWithCovariance
    {
        public const string RosTypeName = "geometry_msgs/msg/PoseWithCovariance";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::PoseWithCovariance_";

        public Pose Pose;
        public double[] Covariance;

        public PoseWithCovariance(Pose pose, double[] covariance)
        {
            Pose = pose;
            Covariance = covariance;
        }

        public override string ToString() => $"PoseWithCovariance(pose={Pose}, covariance=[{(Covariance is null ? 0 : Covariance.Length)}])";
    }

    public sealed class PoseWithCovarianceSerializer : ICdrSerializer<PoseWithCovariance>
    {
        public static readonly PoseWithCovarianceSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in PoseWithCovariance value)
        {
            int total = 0;
            total += PoseSerializer.Instance.GetSerializedSize(in value.Pose);
            total += 36 * 8;
            return total;
        }

        public void Serialize(ref CdrWriter writer, in PoseWithCovariance value)
        {
            PoseSerializer.Instance.Serialize(ref writer, in value.Pose);
            var arrCovariance = value.Covariance ?? new double[36];
            for (int i = 0; i < 36; i++)
            {
                writer.WriteDouble(arrCovariance[i]);
            }
        }

        public void Deserialize(ref CdrReader reader, out PoseWithCovariance value)
        {
            PoseSerializer.Instance.Deserialize(ref reader, out Pose pose);
            var covariance = new double[36];
            for (int i = 0; i < 36; i++)
            {
                covariance[i] = reader.ReadDouble();
            }
            value = new PoseWithCovariance(pose, covariance);
        }

        public void SerializeKey(ref CdrWriter writer, in PoseWithCovariance value)
        {
        }
    }
}
