// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/PoseWithCovarianceStamped
// </auto-generated>
using ROSettaDDS.Cdr;
using ROSettaDDS.Msgs.Std;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/PoseWithCovarianceStamped の C# 表現 (生成コード)。
    /// </summary>
    public struct PoseWithCovarianceStamped
    {
        public const string RosTypeName = "geometry_msgs/msg/PoseWithCovarianceStamped";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::PoseWithCovarianceStamped_";

        public Header Header;
        public PoseWithCovariance Pose;

        public PoseWithCovarianceStamped(Header header, PoseWithCovariance pose)
        {
            Header = header;
            Pose = pose;
        }

        public override string ToString() => $"PoseWithCovarianceStamped(header={Header}, pose={Pose})";
    }

    public sealed class PoseWithCovarianceStampedSerializer : ICdrSerializer<PoseWithCovarianceStamped>
    {
        public static readonly PoseWithCovarianceStampedSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in PoseWithCovarianceStamped value)
        {
            int total = 0;
            total += HeaderSerializer.Instance.GetSerializedSize(in value.Header);
            total += 7;
            total += PoseWithCovarianceSerializer.Instance.GetSerializedSize(in value.Pose);
            return total;
        }

        public void Serialize(ref CdrWriter writer, in PoseWithCovarianceStamped value)
        {
            HeaderSerializer.Instance.Serialize(ref writer, in value.Header);
            PoseWithCovarianceSerializer.Instance.Serialize(ref writer, in value.Pose);
        }

        public void Deserialize(ref CdrReader reader, out PoseWithCovarianceStamped value)
        {
            HeaderSerializer.Instance.Deserialize(ref reader, out Header header);
            PoseWithCovarianceSerializer.Instance.Deserialize(ref reader, out PoseWithCovariance pose);
            value = new PoseWithCovarianceStamped(header, pose);
        }

        public void SerializeKey(ref CdrWriter writer, in PoseWithCovarianceStamped value)
        {
        }
    }
}
