// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/Pose2D
// </auto-generated>
using ROSettaDDS.Cdr;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/Pose2D の C# 表現 (生成コード)。
    /// </summary>
    public struct Pose2D
    {
        public const string RosTypeName = "geometry_msgs/msg/Pose2D";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::Pose2D_";

        public double X;
        public double Y;
        public double Theta;

        public Pose2D(double x, double y, double theta)
        {
            X = x;
            Y = y;
            Theta = theta;
        }

        public override string ToString() => $"Pose2D(x={X}, y={Y}, theta={Theta})";
    }

    public sealed class Pose2DSerializer : ICdrSerializer<Pose2D>
    {
        public static readonly Pose2DSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in Pose2D value)
        {
            int total = 0;
            total += 8;
            total += 8;
            total += 8;
            return total;
        }

        public void Serialize(ref CdrWriter writer, in Pose2D value)
        {
            writer.WriteDouble(value.X);
            writer.WriteDouble(value.Y);
            writer.WriteDouble(value.Theta);
        }

        public void Deserialize(ref CdrReader reader, out Pose2D value)
        {
            double x = reader.ReadDouble();
            double y = reader.ReadDouble();
            double theta = reader.ReadDouble();
            value = new Pose2D(x, y, theta);
        }

        public void SerializeKey(ref CdrWriter writer, in Pose2D value)
        {
        }
    }
}
