// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/PoseArray
// </auto-generated>
using ROSettaDDS.Cdr;
using ROSettaDDS.Msgs.Std;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/PoseArray の C# 表現 (生成コード)。
    /// </summary>
    public struct PoseArray
    {
        public const string RosTypeName = "geometry_msgs/msg/PoseArray";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::PoseArray_";

        public Header Header;
        public Pose[] Poses;

        public PoseArray(Header header, Pose[] poses)
        {
            Header = header;
            Poses = poses;
        }

        public override string ToString() => $"PoseArray(header={Header}, poses=[{(Poses is null ? 0 : Poses.Length)}])";
    }

    public sealed class PoseArraySerializer : ICdrSerializer<PoseArray>
    {
        public static readonly PoseArraySerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in PoseArray value)
        {
            int total = 0;
            total += HeaderSerializer.Instance.GetSerializedSize(in value.Header);
            total += 3;
            total += 4;
            if (value.Poses is not null)
            {
                var serPoses = PoseSerializer.Instance;
                foreach (ref readonly var ePoses in value.Poses.AsSpan())
                {
                    total += 7;
                    total += serPoses.GetSerializedSize(in ePoses);
                }
            }
            return total;
        }

        public void Serialize(ref CdrWriter writer, in PoseArray value)
        {
            HeaderSerializer.Instance.Serialize(ref writer, in value.Header);
            var arrPoses = value.Poses ?? System.Array.Empty<Pose>();
            writer.WriteSequenceLength(arrPoses.Length);
            foreach (var ePoses in arrPoses)
            {
                PoseSerializer.Instance.Serialize(ref writer, in ePoses);
            }
        }

        public void Deserialize(ref CdrReader reader, out PoseArray value)
        {
            HeaderSerializer.Instance.Deserialize(ref reader, out Header header);
            int posesCount = reader.ReadSequenceLength();
            var poses = posesCount == 0 ? System.Array.Empty<Pose>() : new Pose[posesCount];
            for (int i = 0; i < posesCount; i++)
            {
                PoseSerializer.Instance.Deserialize(ref reader, out poses[i]);
            }
            value = new PoseArray(header, poses);
        }

        public void SerializeKey(ref CdrWriter writer, in PoseArray value)
        {
        }
    }
}
