// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/QuaternionStamped
// </auto-generated>
using ROSettaDDS.Cdr;
using ROSettaDDS.Msgs.Std;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/QuaternionStamped の C# 表現 (生成コード)。
    /// </summary>
    public struct QuaternionStamped
    {
        public const string RosTypeName = "geometry_msgs/msg/QuaternionStamped";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::QuaternionStamped_";

        public Header Header;
        public Quaternion Quaternion;

        public QuaternionStamped(Header header, Quaternion quaternion)
        {
            Header = header;
            Quaternion = quaternion;
        }

        public override string ToString() => $"QuaternionStamped(header={Header}, quaternion={Quaternion})";
    }

    public sealed class QuaternionStampedSerializer : ICdrSerializer<QuaternionStamped>
    {
        public static readonly QuaternionStampedSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in QuaternionStamped value)
        {
            int total = 0;
            total += HeaderSerializer.Instance.GetSerializedSize(in value.Header);
            total += 7;
            total += QuaternionSerializer.Instance.GetSerializedSize(in value.Quaternion);
            return total;
        }

        public void Serialize(ref CdrWriter writer, in QuaternionStamped value)
        {
            HeaderSerializer.Instance.Serialize(ref writer, in value.Header);
            QuaternionSerializer.Instance.Serialize(ref writer, in value.Quaternion);
        }

        public void Deserialize(ref CdrReader reader, out QuaternionStamped value)
        {
            HeaderSerializer.Instance.Deserialize(ref reader, out Header header);
            QuaternionSerializer.Instance.Deserialize(ref reader, out Quaternion quaternion);
            value = new QuaternionStamped(header, quaternion);
        }

        public void SerializeKey(ref CdrWriter writer, in QuaternionStamped value)
        {
        }
    }
}
