// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/Transform
// </auto-generated>
using ROSettaDDS.Cdr;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/Transform の C# 表現 (生成コード)。
    /// </summary>
    public struct Transform
    {
        public const string RosTypeName = "geometry_msgs/msg/Transform";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::Transform_";

        public Vector3 Translation;
        public Quaternion Rotation;

        public Transform(Vector3 translation, Quaternion rotation)
        {
            Translation = translation;
            Rotation = rotation;
        }

        public override string ToString() => $"Transform(translation={Translation}, rotation={Rotation})";
    }

    public sealed class TransformSerializer : ICdrSerializer<Transform>
    {
        public static readonly TransformSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in Transform value)
        {
            int total = 0;
            total += Vector3Serializer.Instance.GetSerializedSize(in value.Translation);
            total += QuaternionSerializer.Instance.GetSerializedSize(in value.Rotation);
            return total;
        }

        public void Serialize(ref CdrWriter writer, in Transform value)
        {
            Vector3Serializer.Instance.Serialize(ref writer, in value.Translation);
            QuaternionSerializer.Instance.Serialize(ref writer, in value.Rotation);
        }

        public void Deserialize(ref CdrReader reader, out Transform value)
        {
            Vector3Serializer.Instance.Deserialize(ref reader, out Vector3 translation);
            QuaternionSerializer.Instance.Deserialize(ref reader, out Quaternion rotation);
            value = new Transform(translation, rotation);
        }

        public void SerializeKey(ref CdrWriter writer, in Transform value)
        {
        }
    }
}
