// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/TransformStamped
// </auto-generated>
using ROSettaDDS.Cdr;
using ROSettaDDS.Msgs.Std;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/TransformStamped の C# 表現 (生成コード)。
    /// </summary>
    public struct TransformStamped
    {
        public const string RosTypeName = "geometry_msgs/msg/TransformStamped";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::TransformStamped_";

        public Header Header;
        public string ChildFrameId;
        public Transform Transform;

        public TransformStamped(Header header, string childFrameId, Transform transform)
        {
            Header = header;
            ChildFrameId = childFrameId;
            Transform = transform;
        }

        public override string ToString() => $"TransformStamped(header={Header}, child_frame_id={ChildFrameId}, transform={Transform})";
    }

    public sealed class TransformStampedSerializer : ICdrSerializer<TransformStamped>
    {
        public static readonly TransformStampedSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in TransformStamped value)
        {
            int total = 0;
            total += HeaderSerializer.Instance.GetSerializedSize(in value.Header);
            total += 3;
            int lenChildFrameId = value.ChildFrameId is null ? 0 : System.Text.Encoding.UTF8.GetByteCount(value.ChildFrameId);
            total += 4 + lenChildFrameId + 1;
            total += 7;
            total += TransformSerializer.Instance.GetSerializedSize(in value.Transform);
            return total;
        }

        public void Serialize(ref CdrWriter writer, in TransformStamped value)
        {
            HeaderSerializer.Instance.Serialize(ref writer, in value.Header);
            writer.WriteString(value.ChildFrameId);
            TransformSerializer.Instance.Serialize(ref writer, in value.Transform);
        }

        public void Deserialize(ref CdrReader reader, out TransformStamped value)
        {
            HeaderSerializer.Instance.Deserialize(ref reader, out Header header);
            string childFrameId = reader.ReadString();
            TransformSerializer.Instance.Deserialize(ref reader, out Transform transform);
            value = new TransformStamped(header, childFrameId, transform);
        }

        public void SerializeKey(ref CdrWriter writer, in TransformStamped value)
        {
        }
    }
}
