// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/TwistWithCovariance
// </auto-generated>
using ROSettaDDS.Cdr;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/TwistWithCovariance の C# 表現 (生成コード)。
    /// </summary>
    public struct TwistWithCovariance
    {
        public const string RosTypeName = "geometry_msgs/msg/TwistWithCovariance";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::TwistWithCovariance_";

        public Twist Twist;
        public double[] Covariance;

        public TwistWithCovariance(Twist twist, double[] covariance)
        {
            Twist = twist;
            Covariance = covariance;
        }

        public override string ToString() => $"TwistWithCovariance(twist={Twist}, covariance=[{(Covariance is null ? 0 : Covariance.Length)}])";
    }

    public sealed class TwistWithCovarianceSerializer : ICdrSerializer<TwistWithCovariance>
    {
        public static readonly TwistWithCovarianceSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in TwistWithCovariance value)
        {
            int total = 0;
            total += TwistSerializer.Instance.GetSerializedSize(in value.Twist);
            total += 36 * 8;
            return total;
        }

        public void Serialize(ref CdrWriter writer, in TwistWithCovariance value)
        {
            TwistSerializer.Instance.Serialize(ref writer, in value.Twist);
            var arrCovariance = value.Covariance ?? new double[36];
            for (int i = 0; i < 36; i++)
            {
                writer.WriteDouble(arrCovariance[i]);
            }
        }

        public void Deserialize(ref CdrReader reader, out TwistWithCovariance value)
        {
            TwistSerializer.Instance.Deserialize(ref reader, out Twist twist);
            var covariance = new double[36];
            for (int i = 0; i < 36; i++)
            {
                covariance[i] = reader.ReadDouble();
            }
            value = new TwistWithCovariance(twist, covariance);
        }

        public void SerializeKey(ref CdrWriter writer, in TwistWithCovariance value)
        {
        }
    }
}
