// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/TwistWithCovarianceStamped
// </auto-generated>
using ROSettaDDS.Cdr;
using ROSettaDDS.Msgs.Std;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/TwistWithCovarianceStamped の C# 表現 (生成コード)。
    /// </summary>
    public struct TwistWithCovarianceStamped
    {
        public const string RosTypeName = "geometry_msgs/msg/TwistWithCovarianceStamped";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::TwistWithCovarianceStamped_";

        public Header Header;
        public TwistWithCovariance Twist;

        public TwistWithCovarianceStamped(Header header, TwistWithCovariance twist)
        {
            Header = header;
            Twist = twist;
        }

        public override string ToString() => $"TwistWithCovarianceStamped(header={Header}, twist={Twist})";
    }

    public sealed class TwistWithCovarianceStampedSerializer : ICdrSerializer<TwistWithCovarianceStamped>
    {
        public static readonly TwistWithCovarianceStampedSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in TwistWithCovarianceStamped value)
        {
            int total = 0;
            total += HeaderSerializer.Instance.GetSerializedSize(in value.Header);
            total += 7;
            total += TwistWithCovarianceSerializer.Instance.GetSerializedSize(in value.Twist);
            return total;
        }

        public void Serialize(ref CdrWriter writer, in TwistWithCovarianceStamped value)
        {
            HeaderSerializer.Instance.Serialize(ref writer, in value.Header);
            TwistWithCovarianceSerializer.Instance.Serialize(ref writer, in value.Twist);
        }

        public void Deserialize(ref CdrReader reader, out TwistWithCovarianceStamped value)
        {
            HeaderSerializer.Instance.Deserialize(ref reader, out Header header);
            TwistWithCovarianceSerializer.Instance.Deserialize(ref reader, out TwistWithCovariance twist);
            value = new TwistWithCovarianceStamped(header, twist);
        }

        public void SerializeKey(ref CdrWriter writer, in TwistWithCovarianceStamped value)
        {
        }
    }
}
