// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/TwistStamped
// </auto-generated>
using ROSettaDDS.Cdr;
using ROSettaDDS.Msgs.Std;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/TwistStamped の C# 表現 (生成コード)。
    /// </summary>
    public struct TwistStamped
    {
        public const string RosTypeName = "geometry_msgs/msg/TwistStamped";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::TwistStamped_";

        public Header Header;
        public Twist Twist;

        public TwistStamped(Header header, Twist twist)
        {
            Header = header;
            Twist = twist;
        }

        public override string ToString() => $"TwistStamped(header={Header}, twist={Twist})";
    }

    public sealed class TwistStampedSerializer : ICdrSerializer<TwistStamped>
    {
        public static readonly TwistStampedSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in TwistStamped value)
        {
            int total = 0;
            total += HeaderSerializer.Instance.GetSerializedSize(in value.Header);
            total += 7;
            total += TwistSerializer.Instance.GetSerializedSize(in value.Twist);
            return total;
        }

        public void Serialize(ref CdrWriter writer, in TwistStamped value)
        {
            HeaderSerializer.Instance.Serialize(ref writer, in value.Header);
            TwistSerializer.Instance.Serialize(ref writer, in value.Twist);
        }

        public void Deserialize(ref CdrReader reader, out TwistStamped value)
        {
            HeaderSerializer.Instance.Deserialize(ref reader, out Header header);
            TwistSerializer.Instance.Deserialize(ref reader, out Twist twist);
            value = new TwistStamped(header, twist);
        }

        public void SerializeKey(ref CdrWriter writer, in TwistStamped value)
        {
        }
    }
}
