// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/Vector3Stamped
// </auto-generated>
using ROSettaDDS.Cdr;
using ROSettaDDS.Msgs.Std;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/Vector3Stamped の C# 表現 (生成コード)。
    /// </summary>
    public struct Vector3Stamped
    {
        public const string RosTypeName = "geometry_msgs/msg/Vector3Stamped";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::Vector3Stamped_";

        public Header Header;
        public Vector3 Vector;

        public Vector3Stamped(Header header, Vector3 vector)
        {
            Header = header;
            Vector = vector;
        }

        public override string ToString() => $"Vector3Stamped(header={Header}, vector={Vector})";
    }

    public sealed class Vector3StampedSerializer : ICdrSerializer<Vector3Stamped>
    {
        public static readonly Vector3StampedSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in Vector3Stamped value)
        {
            int total = 0;
            total += HeaderSerializer.Instance.GetSerializedSize(in value.Header);
            total += 7;
            total += Vector3Serializer.Instance.GetSerializedSize(in value.Vector);
            return total;
        }

        public void Serialize(ref CdrWriter writer, in Vector3Stamped value)
        {
            HeaderSerializer.Instance.Serialize(ref writer, in value.Header);
            Vector3Serializer.Instance.Serialize(ref writer, in value.Vector);
        }

        public void Deserialize(ref CdrReader reader, out Vector3Stamped value)
        {
            HeaderSerializer.Instance.Deserialize(ref reader, out Header header);
            Vector3Serializer.Instance.Deserialize(ref reader, out Vector3 vector);
            value = new Vector3Stamped(header, vector);
        }

        public void SerializeKey(ref CdrWriter writer, in Vector3Stamped value)
        {
        }
    }
}
