// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/WrenchStamped
// </auto-generated>
using ROSettaDDS.Cdr;
using ROSettaDDS.Msgs.Std;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/WrenchStamped の C# 表現 (生成コード)。
    /// </summary>
    public struct WrenchStamped
    {
        public const string RosTypeName = "geometry_msgs/msg/WrenchStamped";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::WrenchStamped_";

        public Header Header;
        public Wrench Wrench;

        public WrenchStamped(Header header, Wrench wrench)
        {
            Header = header;
            Wrench = wrench;
        }

        public override string ToString() => $"WrenchStamped(header={Header}, wrench={Wrench})";
    }

    public sealed class WrenchStampedSerializer : ICdrSerializer<WrenchStamped>
    {
        public static readonly WrenchStampedSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in WrenchStamped value)
        {
            int total = 0;
            total += HeaderSerializer.Instance.GetSerializedSize(in value.Header);
            total += 7;
            total += WrenchSerializer.Instance.GetSerializedSize(in value.Wrench);
            return total;
        }

        public void Serialize(ref CdrWriter writer, in WrenchStamped value)
        {
            HeaderSerializer.Instance.Serialize(ref writer, in value.Header);
            WrenchSerializer.Instance.Serialize(ref writer, in value.Wrench);
        }

        public void Deserialize(ref CdrReader reader, out WrenchStamped value)
        {
            HeaderSerializer.Instance.Deserialize(ref reader, out Header header);
            WrenchSerializer.Instance.Deserialize(ref reader, out Wrench wrench);
            value = new WrenchStamped(header, wrench);
        }

        public void SerializeKey(ref CdrWriter writer, in WrenchStamped value)
        {
        }
    }
}
