// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/Wrench
// </auto-generated>
using ROSettaDDS.Cdr;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/Wrench の C# 表現 (生成コード)。
    /// </summary>
    public struct Wrench
    {
        public const string RosTypeName = "geometry_msgs/msg/Wrench";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::Wrench_";

        public Vector3 Force;
        public Vector3 Torque;

        public Wrench(Vector3 force, Vector3 torque)
        {
            Force = force;
            Torque = torque;
        }

        public override string ToString() => $"Wrench(force={Force}, torque={Torque})";
    }

    public sealed class WrenchSerializer : ICdrSerializer<Wrench>
    {
        public static readonly WrenchSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in Wrench value)
        {
            int total = 0;
            total += Vector3Serializer.Instance.GetSerializedSize(in value.Force);
            total += Vector3Serializer.Instance.GetSerializedSize(in value.Torque);
            return total;
        }

        public void Serialize(ref CdrWriter writer, in Wrench value)
        {
            Vector3Serializer.Instance.Serialize(ref writer, in value.Force);
            Vector3Serializer.Instance.Serialize(ref writer, in value.Torque);
        }

        public void Deserialize(ref CdrReader reader, out Wrench value)
        {
            Vector3Serializer.Instance.Deserialize(ref reader, out Vector3 force);
            Vector3Serializer.Instance.Deserialize(ref reader, out Vector3 torque);
            value = new Wrench(force, torque);
        }

        public void SerializeKey(ref CdrWriter writer, in Wrench value)
        {
        }
    }
}
